services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            target: prod
            args:
                WWWUSER: ${WWWUSER}
                WWWGROUP: ${WWWGROUP}
        restart: always
        container_name: h2-hrms-app
        working_dir: /var/www
        volumes:
            - .:/var/www:cached
            - .docker/php/supervisord.conf:/etc/supervisord.conf
            - .docker/php/supervisor.conf:/etc/supervisor/conf.d/supervisor.conf
        depends_on:
            - postgres
            - redis
        networks:
            - h2-hrms-network

    # nginx
    nginx:
        image: nginx:alpine
        container_name: h2-hrms-nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - h2-hrms-network

    # postgress
    postgres:
        image: "postgres:17"
        ports:
            - "7000:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - h2-hrms-network

    redis:
        image: redis:alpine
        container_name: h2-hrms-redis
        restart: always
        volumes:
            - redis_data:/data
        networks:
            - h2-hrms-network

    mailpit:
        image: axllent/mailpit
        container_name: h2-hrms-mailpit
        restart: always
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - h2-hrms-network

volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local

networks:
    h2-hrms-network:
        driver: bridge
